apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ldonleycb/hackers-organized
    newName: ldonleycb/hackers-organized
    newTag: latest
