apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  test:
    steps:
      - uses: cloudbees-io/ghactions-run-workflow@v2
        name: Run GHA Workflow
        kind: test
        with:
          token: ${{ secrets.GH_TOKEN }}
          org-name: cloudbees-days
          repo-name: hackers-organized
          branch-name: main
          workflow-name: test-and-build-image
          test-type: JUNIT
          test-result-location: junit.xml
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        kind: build
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Configure container registry credentials
        id: dockerconfig
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: cloudbees-io/kaniko@v1
        name: Build container image
        kind: build
        with:
          destination: ${{ secrets.DOCKERHUB_USER }}/hackers-organized:1.0.1,${{ secrets.DOCKERHUB_USER }}/hackers-organized:latest
          tar-path: container-image.tar
      - uses: calculi-corp/assets-plugin-chain-utils/upload-binary@v1
        name: Upload binary from container build
        id: upload-binary
        with:
          file-path: container-image.tar
          file-type: BINARY_CONTAINER
          debug: "true"
    needs: test
  scan:
    steps:
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        name: Scan with SonarQube
        kind: scan
        with:
          language: LANGUAGE_JS
  deploy:
    environment: DOW Production
    steps:
      - uses: cloudbees-io/kubernetes-create-resource@v1
        name: Deploy to cluster
        kind: deploy
        with:
          file-path: deploy.yaml
          namespace: hackers-organized-prod
    needs:
      - build
      - scan
