apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  test:
    steps:
      - uses: cloudbees-io/ghactions-run-workflow@v2
        name: Run GHA Workflow
        with:
          token: ${{ secrets.GH_TOKEN }}
          org-name: cloudbees-days
          repo-name: hackers-organized
          branch-name: main
          workflow-name: test-and-build-image
          test-type: JUNIT
          test-result-location: junit.xml


  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ secrets.DOCKERHUB_USER }}/hackers-organized:1.0.1,${{ secrets.DOCKERHUB_USER }}/hackers-organized:latest
          tar-path: container-image.tar

      - id: upload-binary
        name: Upload binary from container build
        uses: calculi-corp/assets-plugin-chain-utils/upload-binary@v1
        with:
          file-path: container-image.tar
          file-type: BINARY_CONTAINER
          debug: "true"

  scan:
    steps:
      - name: Scan with SonarQube
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        with:
          language: LANGUAGE_JS
