apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: ghactions-preconfigured-test
        name: Run GHA
        kind: build
        with:
          token: ${{ secrets.GH_TOKEN }}
          org-name: cloudbees-days
          repo-name: hackers-organized
          branch-name: main
          workflow-name: Test and build
          test-type: JUNIT
