apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: cloudbees-io/ghactions-run-workflow@v2
        name: Run GHA Workflow
        with:
          token: ${{ secrets.GH_TOKEN }}
          org-name: cloudbees-days
          repo-name: hackers-organized
          branch-name: main
          workflow-name: test-and-build-image
          test-type: JUNIT
          test-result-location: junit.xml
